### ISSUE TITLE
VPEEK doesn't support evaulation on the 2nd param

### ISSUE THREAD

**Issue by oziphantom** [commanderx16/x16-rom#1] opened 2019-09-07 11:07 UTC
VPEEK(num,num) ; fine
VPEEK(var,var) ; fine
VPEEK(var+something, var) ; fine
VPEEK(anything,var+something); Syntax error
j= i + 3:VPEEK(anything,j) ; Bad Subscript Error

**Comment by mist64** [comment] 2019-09-07 11:10
Can you try with r29? This should be fixed.

**Comment by oziphantom** [comment] 2019-09-07 11:11
I'm on r29, it does seem to support some cases but not all...

**Comment by mist64** [comment] 2019-09-07 11:14
In the laste example, the error is correct, since VPEEK is a function and you are using it as a statement.

**Comment by oziphantom** [comment] 2019-09-07 11:55
it was a shortened example, 
but it seems there is something else going on... 
![image](https://user-images.githubusercontent.com/7146763/64474575-181a2680-d1ba-11e9-90e7-584b0dd04847.png)

**Comment by mist64** [comment] 2019-09-08 10:10
Reproduced.

**Comment by mist64** [comment] 2019-09-08 10:14
Minimal test case:

      PRINTVPEEK(0,0),VPEEK(11,0)

The second VPEEK is not tokenized. The encoded BASIC program contains the ASCII text "VPEEK".

**Comment by mist64** [comment] 2019-09-08 10:19
Weird, now it doesn't reproduce any more!

**Comment by mist64** [comment] 2019-09-08 10:25
Ah, this was fixed after the r29 release. It will be fixed in r30. In the meantime, try a newer [rom.bin.zip](https://github.com/commanderx16/x16-rom/files/3587511/rom.bin.zip).

**Closed by mist64** 2019-09-08 10:25 UTC
