### ISSUE TITLE
Uncommanded change of character set triggered by using PETSCII color codes in PRINT after using SCREEN and COLOR

### ISSUE THREAD

**Issue by fluffymormegil** [commanderx16/x16-rom#91] opened 2019-11-23 12:13 UTC
The following sequence of BASIC commands causes an unrequested switch to ISO-8859-15 mode:

10 SCREEN 0:COLOR 15,0:PRINT"\X93\X9B"

**Comment by fluffymormegil** [comment] 2019-11-27 01:47
On closer investigation:

Setting the foreground color to 15 (light grey) while the background colour is black switches to the ISO-8859-15 charset and sets the input case to lowercase (making it annoying to type further basic statements). If the background colour is anything else, setting foreground colour 15 is fine.

Setting the foreground color to 14 (light blue) while the background colour is black switches to mixed-case PETSCII. If the background colour is anything else, setting foreground colour 14 is fine.

**Comment by mist64** [comment] 2019-12-21 11:10
I can't reproduce this on r35.

**Comment by fluffymormegil** [comment] 2019-12-25 22:51
Neither can I, but not in a good way.
As far as I can tell, the COLOR statement doesn't support background colour changes at all on r35.

**Comment by mist64** [comment] 2022-03-22 20:51
I can't reproduce any of this on r38. I tried the test line with different combinations of numbers, and it always changed foreground and background, and never switched into ISO mode. Closing. (Feel free to reopen if there is new information!)

**Closed by mist64** 2022-03-22 20:51 UTC
Labels: bug, [KERNAL], r39
