### ISSUE TITLE
Switching from SCREEN 128 to 2 doesn't disable graphics layer, doesn't set proper colors

### ISSUE THREAD

**Issue by Robert-Lloyd3** [commanderx16/x16-rom#76] opened 2019-11-03 23:00 UTC
Switching between SCREEN 0 and SCREEN 2 modes preserves the X16's initial power-on white-text-on-blue power-on color scheme.
Switching to SCREEN 128 mode inverts the initial power-on mode, displaying a blue-text-on-white color scheme.
Switching back to SCREEN 0 or SCREEN 2 results in a blue-text-on-black color scheme.

This is inconsistent behavior.

Initial Mode | New Mode | Text Foreground | Background
-- | -- | -- | --
[POWER OFF] | 2 | White | Blue
0 | 2 | White | Blue
2 | 0 | White | Blue
0 | 128 | Blue | White
2 | 128 | Blue | White
128 | 0 | Blue | Black
128 | 2 | Blue | Black

**Comment by mist64** [comment] 2022-03-22 20:57
Reproduced.

**Comment by mist64** [comment] 2022-03-22 21:14
When switching to graphics mode, the line 237 of kernal/drivers/x16/screen.s sets the foreground color to 14 (light blue) and the background color to 0, which is transparent, which makes the underlying bitmap layer visible.

There are two bugs here:

* Switching from graphics mode to any text mode should change the colors to white-on-blue.
* It seems color 0 is still translucent, so we can see the layer behind text mode. Steps to reproduce:

```
SCREEN128
LINE0,0,100,100
SCREEN2

```

**Comment by mist64** [comment] 2022-03-24 21:27
This was good in r36, and bad in r37.

**Comment by mist64** [comment] 2022-03-24 21:43
And fixed by 959eaf7576eb160469acf7b9b63e4cb74a9ab7a1

**Comment by mist64** [comment] 2022-03-24 21:49
What's fixed is the garbage remaining on the screen. What isn't fixed:
* after `SCREEN128:SCREEN2`, color 0, which should be black, is white
* this survives a reset!
* the cursor color is still ltblue-on-white, but should be white-on-blue

**Comment by mist64** [comment] 2022-03-25 06:46
The remaining problems 1 and 2 were caused by an emulator bug, fixed in https://github.com/commanderx16/x16-emulator/commit/85724f303eab0fcacec4b3f583b8f7cd828bd186

**Comment by mist64** [comment] 2022-03-25 07:02
The text color issue was fixed by 5a1102d.

**Closed** 2022-03-25 07:02 UTC
Labels: bug, [KERNAL], r39
